# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6d2d88855acff968fd39a396f77570bd15c7e0c2c30c3e66af7169425c12fad3d55ec6b34a6e548634a5c59200904819b1f5ddb5d0654e372dab74b0049ac06

test:
  secret_key_base: 846415eb5d10d0f89856512c450da2c77571c1cfd371943f8bb96bd2d1598d91f98ca926a0e64e885fe30ad23b5c0db633bcb3a7fc82b4496ed7bb070a30b9bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
